name: Test Ray Serve API

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        run: bash <(curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.21
        shell: bash
      - name: Check workflow files
        run: ./actionlint
        shell: bash
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
        with:
          python-version: "3.10"
      - run: poetry run tox
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

  pre-commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python-poetry-env
      - run: poetry run pre-commit run --all-files
